FROM python:3.9-slim
WORKDIR /app

#авторизация для скачивания зависимостей из закрытых репозиториев
ARG ARG_PASSWORD_DEFAULT=P@55w0rD

#авторизация для скачивания зависимостей из закрытых репозиториев
ARG ARG_PASSWORD_CLI

ENV PASSWORD=${ARG_PASSWORD_CLI}